[package]
name = "pyo3-calculate-pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "calculate_pi"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.14.4"
features = ["extension-module"]
