[package]
name = "art"
version = "0.1.0"
edition = "2021"
description = "A library for your art projects."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
